### ISSUE TITLE
Play Kubernetes YAML throws application/tar is not supported.

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#10010]
### Bug description

Trying to create a pod from .yaml file (created by the same podman version) throws the following error: 
![Image](https://github.com/user-attachments/assets/22bd91c6-8115-4abf-a4c8-a7ad4d9e1f1e)

If I play through CLI, it works. 

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Relevant log output

```shell

```

### Additional context

The yaml file content: 
```
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-20T11:22:51Z"
  labels:
    app: happycerf-pod
  name: happycerf-pod
spec:
  containers:
  - args:
    - /usr/bin/run-httpd
    env:
    - name: TERM
      value: xterm
    image: docker.io/alfiilham26/httpd-24:latest
    name: happycerf
    ports:
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 8443
      hostPort: 8443
    securityContext:
      runAsNonRoot: true
    stdin: true
    tty: true
```
