### ISSUE TITLE
Add Ability to Specify Kind Cluster Configuration

### ISSUE THREAD

**Issue by damaestro** [containers/podman-desktop#10268]
### Is your enhancement related to a problem? Please describe

When creating a KinD cluster, there is not way to customize the install other than manually setting up the cluster. For example, when using podman machine:

```
podman machine init -m 16384 --rootful --now
podman machine ssh
```

Install KinD (while connected to the VM):

```
# For AMD64 / x86_64
[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-amd64
# For ARM64
[ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-arm64
chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind
```

Create a two-node cluster with host port bindings:

```
kind create cluster --name my-cluster --config=- <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  - containerPort: 8443
    hostPort: 8443
    protocol: TCP
EOF
```

### Describe the solution you'd like

Add the ability to pass in a configuration for the `kind create cluster`.

### Additional context

The primary reason for this is to be able to run a multi-node cluster and specify different networking layouts for more advanced usage.
