### ISSUE TITLE
Doc: Add a troubleshooting section in the guide

### ISSUE THREAD

**Issue by shipsing** [containers/podman-desktop#10275]
### Is your enhancement related to a problem? Please describe

There is a constant issue with AWS related k8s clusters and the user gets this error: `Error: spawnSync aws ENOENT`

### Describe the solution you'd like

There is a workaround available for now and we need to document it. 
More details are in [this thread](https://redhat-internal.slack.com/archives/C032QG6EQE7/p1732740023179679?thread_ts=1732733031.520979&cid=C032QG6EQE7). 
[This issue](https://github.com/podman-desktop/podman-desktop/issues/10081) is open. A capability will be added to Podman Desktop to check if the command defined for authentication is accessible from the Podman context. If not, a warning will be displayed on the Settings > Kubernetes page to notify users.

**Comment by ibre5041** [comment]
Similar error occurs on OCI cluster: `Error: spawnSync oci ENOENT`

Excerpt from kube config

```
users:
- name: user-x
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - ce
      - cluster
      - generate-token
      - "--cluster-id"
      - ocid1.cluster.oc1.ap-mumbai-1.aaaaaaaa
      - "--region"
      - ap-mumbai-1
      - "--config-file"
      - /Users/ibre5041/.oci/config
      - "--profile"
      - DEFAULT
      - "--auth"
      - security_token
      command: oci
      env: []
      interactiveMode: IfAvailable
      provideClusterInfo: false

```
