### ISSUE TITLE
feat: represent non accessible Kubernetes resources in the frontend

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#10655]
### Is your feature request related to a problem? Please describe

Backend provides the information for each Kubernetes resource kind if the kind is accessible or not by the user. 

### Describe the solution you'd like

Represent this accessibility, with the help of #10385 

### Additional context

- [x] Kubernetes Contexts List: https://github.com/podman-desktop/podman-desktop/pull/10856
- [ ] Kubernetes dashboard: 
  - [x] https://github.com/podman-desktop/podman-desktop/issues/11106

~- [ ]  [ ] Kubernetes Resources (deployment, etc) List: https://github.com/podman-desktop/podman-desktop/issues/11107~ (tracked separately)

#### How to create a context with a specific user and give this user some permissions

Create a new user for a kind cluster: https://medium.com/@lionelvillard/creating-users-in-kind-cluster-6c5ee35db3fe

By default, the user won't have any permissions.

You can give permissions to Pod only with:

```
$ cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user1
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user1
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: user1
  apiGroup: rbac.authorization.k8s.io
EOF
```

Or to Deployment only:

```
cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user1
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user1
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: user1
  apiGroup: rbac.authorization.k8s.io
EOF
```
