### ISSUE TITLE
Error while fetching API groups: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported

### ISSUE THREAD

**Issue by jaggaer-mbugni** [containers/podman-desktop#12114]
### Bug description

I don't know if this is a bug or an enhancement.

It seems https is required to access K8S API, so I cannot access to a cluster using a kubectl proxy.

### Operating system

Windows 11 Enterprise

### Installation Method

Winget (Windows)

### Version

1.17.0

### Steps to reproduce

I'm using a kubectl proxy for accessing to a cluster APIs, using a command like this:
```shell
$ kubectl proxy --port 8001 --reject-paths "^/api/./pods/./attach" --context myk8s
```
In my .kube\config file:
```
apiVersion: v1
kind: Config
clusters:
- name: myk8s-proxy-8001
  cluster:
    server: http://localhost:8001
```

If I use kubectl.exe or other tools like Headlamp, everything works fine.

If I try to access the same cluster using Podman Desktop I get (from log):
```
Error while fetching API groups: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
```

### Relevant log output

```shell
Error while fetching API groups: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
```

**Comment by odockal** [comment]
@jaggaer-mbugni This looks very similar to https://github.com/podman-desktop/podman-desktop/issues/10471, which could be fixed in 1.18.0 release. If you want, you could try the nightly bits if that solves your problem: https://github.com/podman-desktop/prereleases/tags

**Comment by jaggaer-mbugni** [comment]
Ho @odockal, the #10471 doesn't seem the same, note the log:
```
FetchError: request to https://XXX/apis/apps/v1/namespaces/default/deployments failed, reason: Client network socket disconnected before secure TLS connection was established)
```
The client is attempting to connect using `https` protocol, while in my case it refuses to use `http`.

**Comment by jaggaer-mbugni** [comment]
Just tested version v1.18.0. It works now!

From the logs:
```
Error while fetching API groups: Error: HTTP protocol is not allowed when skipTLSVerify is not set or false
```

So, to get it working, I added the `insecure-skip-tls-verify` flag like:
```yaml
clusters:
- name: wsl2-proxy-8001
  cluster:
    insecure-skip-tls-verify: true
    server: http://localhost:8001
```

Thanks
