### ISSUE TITLE
Warn user when the pod cannot be started 

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#1219]
### Is your enhancement related to a problem? Please describe

If you create a pod and try to start it when the YAML is invalid nothing happens.
E.g.
1. i created a new pod using
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-7
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
```
2. try to start it. Nothing happens.
The reason is that `rootlessport cannot expose privileged port 80` but i'm not informed.
In the gif below i click on both pods (one valid, one invalid). the invalid one does not do anything
![Animation](https://user-images.githubusercontent.com/49404737/214008952-51b74efd-6ed9-4367-a030-8865617a558b.gif)

### Describe the solution you'd like

It would be helpful to see an error message to know what's happening
