### ISSUE TITLE
Error printed when creating pod from YAML file but it worked

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#1220]
### Bug description

Not sure if it's a valid bug honestly, maybe it can only be enhanced somehow but if i create a pod/container with a yaml file i see this error

![immagine](https://user-images.githubusercontent.com/49404737/214017786-346c2069-c352-4d8f-b568-b2ca9db857d8.png)

so i expect that it didn't work but, actually, the pod was created and i can play with it. 

### Operating system

Windows 10 

### Version

next (development version)

### Steps to reproduce

1. click on Pod -> Play Kubernetes YAML
2. choose the yaml file. Mine was 
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-11
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 8080
 ```
3. click play
