### ISSUE TITLE
Create GitHub Actions for building container images

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#12758]
### Is your enhancement related to a problem? Please describe

When creating a workflow to create a container image or manifest, I have to refer to another Podman Desktop extension to run the same workflow.

### Describe the solution you'd like

I would prefer to use a specific GitHub Actions, dedicated to build a container image or manifest, based on a Containerfile and a context

**Comment by benoitf** [comment]
for building image AFAIK we're using `redhat-actions/buildah-build`

you want a more high level action ?


```
 name: build builder image
        id: builder-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: minc-extension-builder
          tags: latest ${{ needs.tag.outputs.extVersion }}
          platforms: linux/amd64, linux/arm64
          containerfiles: |
            build/Containerfile.builder
          context: .
          oci: true
```
