### ISSUE TITLE
Kubify: Too many labels

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1316]
### Is your enhancement related to a problem? Please describe

When going from Pod to Kubernetes, there's too many labels (IMO) which aren't needed in the Kubernetes YAML.

```yaml
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/tutorial-db: container
    io.kubernetes.cri-o.ContainerType/tutorial-wp: container
    io.kubernetes.cri-o.SandboxID/tutorial-db: c2d7ef94df03eac80ec7ff46dba40d14a6fbe92ef6de8ccbc865e79d7e194d3
    io.kubernetes.cri-o.SandboxID/tutorial-wp: c2d7ef94df03eac80ec7ff46dba40d14a6fbe92ef6de8ccbc865e79d7e194d3
    io.kubernetes.cri-o.TTY/tutorial-db: "false"
    io.kubernetes.cri-o.TTY/tutorial-wp: "false"
    io.podman.annotations.autoremove/tutorial-db: "FALSE"
    io.podman.annotations.autoremove/tutorial-wp: "FALSE"
    io.podman.annotations.init/tutorial-db: "FALSE"
    io.podman.annotations.init/tutorial-wp: "FALSE"
    io.podman.annotations.privileged/tutorial-db: "FALSE"
    io.podman.annotations.privileged/tutorial-wp: "FALSE"
    io.podman.annotations.publish-all/tutorial-db: "FALSE"
    io.podman.annotations.publish-all/tutorial-wp: "FALSE"
  creationTimestamp: "2023-01-31T10:16:21Z"
  labels:
```

### Describe the solution you'd like

Will be fixed in Podman 4.4 (maybe?). Unable to find issue.
