### ISSUE TITLE
Kubernetes: Add ability to supply domain name for Ingress creation

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2435]
### Is your enhancement related to a problem? Please describe

When creating an Ingress, I am only able to create 1 Ingress as it's being made on the defaultBackend:

```
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: wizardlygoldberg-pod-9000
      port:
        number: 9000
```

As we are using `kind` as our main example.

In the "Deploy to Kubernetes" form, we should have the ability to supply a URL to be used.

### Describe the solution you'd like

Ability to supply a domain name.
