### ISSUE TITLE
Kubernetes: Add ability to create an HTTPS / TLS / Let's Encrypt Ingress.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2436]
### Is your enhancement related to a problem? Please describe

Part 2 of https://github.com/containers/podman-desktop/issues/2435

But we should have the ability to enable TLS / HTTPS connection.

My bare metal cluster supports TLS / HTTPS / Let's Encrypt by default. So whenever we supply / say that we need to use https, it will automatically be setup.

### Describe the solution you'd like

We should provide the ability to create an Ingress with https / let's encrypt. 

This can be implemented by a checkbox which will add the necessary YAML information like so:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: %NAME%
  labels:
    app.kubernetes.io/name: %NAME%
    app.kubernetes.io/instance: %NAME%
  annotations:

    # Nginx-specific for HTTPS usage
    nginx.org/websocket-services: %NAME%
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true'

    # Let's Encrypt
    cert-manager.io/cluster-issuer: letsencrypt-production
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
        - %DOMAIN%
      secretName: %DOMAIN%
  rules:
    - host: %DOMAIN%
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: %NAME%
                port:
```

Since every TLS / HTTPS setup is different, we may have to add the option of "Is this Let's Encrypt?" or even the ability to preview / see the Ingress YAML before deployment so the cluster administrator can preview it / make sure it's correct.
