### ISSUE TITLE
Kubernetes: containers from pods are not showing up

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman-desktop#2800]
### Is your enhancement related to a problem? Please describe

When you inspect a pod, you get a link to the container in the pod:

```
Name:	sleep
Id:	9be0d094-39fe-41a0-9942-f6aac709c336

Containers using this pod:
sleep	containerd://543f36210cf0c1c864301cd368f05c742b43b30163612539ba77d20da2b73d78
```

But clicking the link shows a blank page (no such container engine?).

It also not possible to see what image it is running, or get a link to that.

### Describe the solution you'd like

Probably Podman Desktop needs to learn how to talk to the CRI ?

Then it could list both containers and images, and more pod info.

Currently nothing from containerd is showing up in Podman Desktop:

* #1450

### Describe alternatives you've considered

It is possible to use the command line instead

`docker exec kind-control-plane crictl pods`

```
POD ID              CREATED             STATE               NAME                                         NAMESPACE            ATTEMPT             RUNTIME
...
948376f724c7c       10 days ago         Ready               sleep                                        default              5                   (default)
...
```

`docker exec kind-control-plane crictl ps  --pod 948376f724c7c`

```
CONTAINER           IMAGE               CREATED             STATE               NAME                      ATTEMPT             POD ID              POD
543f36210cf0c       b539af69bc01c       24 minutes ago      Running             sleep                     39                  948376f724c7c       sleep
```

`docker exec kind-control-plane crictl images`

```
IMAGE                                      TAG                  IMAGE ID            SIZE
...
docker.io/library/busybox                  latest               b539af69bc01c       2.6MB
...
```

### Additional context

It is somewhat confusing that the UID is shown as the ID, in the interface.

```yaml
    "id": "948376f724c7cc832535ed85c4a0fe9a6f941ce940ce71797138d5da2ebf60f6",
    "metadata": {
      "attempt": 5,
      "name": "sleep",
      "namespace": "default",
      "uid": "9be0d094-39fe-41a0-9942-f6aac709c336"
    },
```
