### ISSUE TITLE
Play Kubernetes YAML does not error out despite container errors on creation. 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3033]
### Bug description

![Screenshot 2023-06-27 at 2 31 56 PM](https://github.com/containers/podman-desktop/assets/6422176/db941d4a-b035-4848-9ceb-1b8f63bf067d)

See "ContainerErrors".

We are able to successfully deploy, but when the containers are created, we encounter an error (such as a port being taken) but we do not error our or warn the user.

Because this error occurs *after* creation (we create and THEN start), we should at least warn the user that the container has been created, but the port is unavailable.

### Operating system

mac M1

### Installation Method

None

### Version

1.1.0

### Steps to reproduce

Using the following YAML:

```
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.ulimit: nofile=524288:524288,nproc=7248:7248
  creationTimestamp: "2023-06-27T17:47:37Z"
  labels:
    app: reverentrobinson-pod
  name: reverentrobinson-pod
spec:
  containers:
  - image: docker.io/cdrage/helloworld:latest
    name: reverentrobinson
    ports:
    - containerPort: 80
      hostPort: 9000
    tty: true


```

1. Do "Deploy Kubernetes YAML"
2. Select Podman container engine
3. See the json output where there is errors, but there is no visible errors within podman desktop UI
