### ISSUE TITLE
Slow podman command response indicator

### ISSUE THREAD

**Issue by JDUNNIN** [containers/podman-desktop#3243]
### Is your enhancement related to a problem? Please describe

I'm always frustrated when it looks like my containers are not started as the containers panel shows empty, but actually it is that the `podman ps` (or whatever command/API is used under the covers) is slow to respond.

### Describe the solution you'd like

Display a warning overlay or message indicating that retrieving container/image/pod/etc status is taking longer than usual after `n` seconds.

**Comment by benoitf** [comment]
hi @JDUNNIN for now there is not yet an indicator but could you check in Troubleshooting page (now in statusbar with light bulb) the 'stores' section

it should display the time that is taken to update each store (like containers)
can you share values ?


Also we're working on displaying CPU usage of the VM in the tool. I suspect that maybe your VM is too small for the number of containers you might be running
https://github.com/containers/podman-desktop/pull/3111#issuecomment-1622277130

Could you check the average cpu usage (you can use command `podman info` to grab it)

**Comment by JDUNNIN** [comment]
Hi @benoitf that troubleshooting page is helpful, nice update!

The values are all low at moment in ~60ms, I'll take a look when I spot a slow down but know it'll be seconds at least until something gets unblocked.

I spied 3111 a while back, that'll be a nice enhancement.

`podman info` shows this with 0 containers:
```
  cpuUtilization:
    idlePercent: 99.4
    systemPercent: 0.33
    userPercent: 0.27
  cpus: 4
```
With 1 container:
```
  cpuUtilization:
    idlePercent: 98.65
    systemPercent: 0.7
    userPercent: 0.65
```

I can review that also when I see slowdown.
