### ISSUE TITLE
potentially insufficient UIDs or GIDs available in user namespace

### ISSUE THREAD

**Issue by mydeveloperplanet** [containers/podman-desktop#3444]
### Bug description

When building an image via Podman Desktop, I encounter the following error:
`Uploading the build context from /home/.../mypodmanplanet...Can take a while...
Error:(HTTP code 500) server error - potentially insufficient UIDs or GIDs available in user namespace (requested 262143:262143 for /var/tmp/libpod_builder2108531042/bError:Error: (HTTP code 500) server error - potentially insufficient UIDs or GIDs available in user namespace (requested 262143:262143 for /var/tmp/libpod_builder2108531042/build/.git): Check /etc/subuid and /etc/subgid: lchown /var/tmp/libpod_builder2108531042/build/.git: invalid argument `

I can build the image without any problem via CLI: `podman build . --tag mydeveloperplanet/mypodmanplanet:0.0.1-SNAPSHOT -f podman-desktop/1-Dockerfile`

I have extended the UIDs and GIDs for my user. It seems that Podman Desktop is running as a specific other user?

### Operating system

Ubuntu 22.04

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1
I am using Podman 3.4.4

### Steps to reproduce

clone the repo: https://github.com/mydeveloperplanet/mypodmanplanet

build the jar-file: `mvn clean verify`

Use Podman Desktop to build the image:
Dockerfile: podman-desktop/1-Dockerfile
Build context: should be the root of the repository
Image Name: mydeveloperplanet/mypodmanplanet:0.0.1-SNAPSHOT
click Build

I am able to build the image without any problem via CLI:
`podman build . --tag mydeveloperplanet/mypodmanplanet:0.0.1-SNAPSHOT -f podman-desktop/1-Dockerfile`

### Relevant log output

```shell
see above
```

**Comment by benoitf** [comment]
hello @mydeveloperplanet 

Could you check if you're using a rootful podman or rootless with the CLI

On Linux Podman Desktop is always using the rootless connection

**Comment by mydeveloperplanet** [comment]
The rootless version, checked it with `podman system info`. I also see that the gidmap and sidmap are ok, I updated them when I was experimenting with Podman CLI.
```
idMappings:
    gidmap:
    - container_id: 0
      host_id: 1688000513
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1688001497
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
```
