### ISSUE TITLE
website: social media / share cards don't include images

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3613]
### Bug description

Report from @TomSweeneyRedHat :

```
I just posted a link to the Podman Desktop 1.3 announcement from this
page: https://podman-desktop.io/blog/podman-desktop-release-1.3, and
when I posted it to Twitter:

https://twitter.com/Podman_io/status/1693626155989946406

There isn't a default Podman Desktop image as I would have expected. 
Can this be changed for the future?
```

![Screenshot from 2023-08-21 11-22-50](https://github.com/containers/podman-desktop/assets/799683/81acf5b2-e507-4c8c-8dac-b21fdd36578b)

This is something to do with Docusaurus. Looking at the Docusaurus docs, it appears there's an image attribute that gets used for this:

```
---
title: Welcome Docusaurus v2
description: This is my first post on Docusaurus 2.
slug: welcome-docusaurus-v2
authors:
  - name: Joel Marcey
    title: Co-creator of Docusaurus 1
    url: https://github.com/JoelMarcey
    image_url: https://github.com/JoelMarcey.png
  - name: Sébastien Lorber
    title: Docusaurus maintainer
    url: https://sebastienlorber.com
    image_url: https://github.com/slorber.png
tags: [hello, docusaurus-v2]
image: https://i.imgur.com/mErPwqL.png
hide_table_of_contents: false
---
```

It looks like the 1.13 blog doesn't have an image attribute:

```
---
title: Release Notes - Podman Desktop 1.3
description: Podman Desktop 1.3 has been released!
slug: podman-desktop-release-1.3
authors: [dgolovin]
tags: [podman-desktop, release, kubernetes, openshift]
hide_table_of_contents: false
---
```

This might be as simple as adding the `image` attribute to the header metadata of the post, but I  need to figure out how to test it locally bc it seems by default docusaurus isn´t generating / sending the metadata for local yarn builds. I might need to set up a ghpages thing to test.

![Screenshot from 2023-08-21 11-27-17](https://github.com/containers/podman-desktop/assets/799683/8490f772-af96-47bd-831d-c3cafac949f5)
![Screenshot from 2023-08-21 11-27-07](https://github.com/containers/podman-desktop/assets/799683/c0c80423-09df-49a4-aa66-0a115e2cb9f7)

### Operating system

N/A

### Installation Method

None

### Version

1.3.1
