### ISSUE TITLE
Implement E2E test cases using Playwright for Registries adding, authentication and deletion

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#4362]
### Is your enhancement related to a problem? Please describe

Implement test cases covering Registries handling verification, including addition, authentication and deletion.

### Describe the solution you'd like

Cover the following cases:
- valid registry creation and authentication 
- toggle password visibility verification
- edit password verification
- remove registry
- UI components verification (before/after creation, after removal)

**Comment by odockal** [comment]
A code snippet how to use secrets from github repository in github actions workflow:
```
    steps:
    - name: Set the default env. variables
      env:
        DEFAULT_SECRET: 'mysecret'
      run: |
        echo "MY_SECRET=${{ secrets.QUAY_IO_TEST || env.DEFAULT_SECRET }} " >> $GITHUB_ENV 
```

And a code snippet in a typescript test file.
```
...
let quaySecret: string;

beforeAll(async () => {
  pdRunner = new PodmanDesktopRunner();
...
  quaySecret = process.env.MY_SECRET ? process.env.MY_SECRET : 'default';
}
...
```
