### ISSUE TITLE
Design for Ingress/Routes page

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4404]
### Is your enhancement related to a problem? Please describe

Kubernetes!

### Describe the solution you'd like

We need a design for an initial Kubernetes Ingress / Routes page, to be implemented by #4367.

**Comment by ConorC117** [comment]
Link to Ingress/Routes List's Page:
https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/18f3baa5-c6db-81d1-8002-9f756ec487eb?page-id=88a72dea-ea00-80c5-8003-65bac129fecd

**Comment by deboer-tim** [comment]
Current screenshot:
<img width="775" alt="Screenshot 2023-11-07 at 8 38 39 AM" src="https://github.com/containers/podman-desktop/assets/19958075/b77f8c89-2ffe-4d4b-95f7-180d68702acd">

**Comment by benoitf** [comment]
Ingress icon in the mockup makes me feel like it's a shuffle icon

**Comment by deboer-tim** [comment]
Agreed. Really quick idea of how it could be changed, maybe don't even need the box:
![ing](https://github.com/containers/podman-desktop/assets/19958075/b98fe885-b93c-44e1-b5a6-bdfb992119d9)

**Comment by lstocchi** [comment]
@ConorC117 @mairin how should we display an ingress that has multiple rules? Multiple lines with the same ingress name but different host/path/backend, or a single line which contains everything (maybe a row with a greater height)?

If we do the former there would be a problem with the delete action though 🤔 

E.g.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: service1
            port:
              number: 80
  - host: "*.foo.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
```
