### ISSUE TITLE
Pressing "Deploy to Kubernetes" on a Compose example adds extra section to bottom

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4723]
### Bug description

https://github.com/containers/podman-desktop/assets/6422176/72decace-759b-4b98-ae4e-25dff17e593a

Toolbar section being shown for some reason at the bottom of the screen.

### Operating system

mac m1

### Installation Method

None

### Version

1.5.0

### Steps to reproduce

Deploy any Compose example:

```yaml
services:

  redis-master:
    #container_name: redis-master
    image: redis:latest
    ports:
      - "6379"

  redis-replica:
    #container_name: redis-replica
    image: redis:latest
    ports:
      - "6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master

  frontend:
    #container_name: frontend
    image: cdrage/frontend
    #build: ./frontend
    ports:
      - "8080:8080"
```

Click on `Deploy to Kubernetes`

Scroll to the bottom.
