### ISSUE TITLE
Converting Compose example to Kubernetes is giving odd container names.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4724]
### Bug description

When I press Deploy to Kubernetes on a Compose group, `compose-` is appended to the start of the container names rather than the actual container names that are being used.

### Operating system

mac M1

### Installation Method

None

### Version

1.5.0

### Steps to reproduce

1. Deploy a Compose YAML example 

```yaml
services:

  redis-master:
    image: redis:latest
    ports:
      - "6379"

  redis-replica:
    image: redis:latest
    ports:
      - "6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master

  frontend:
    image: cdrage/frontend
    #build: ./frontend
    ports:
      - "8080:8080"
 ```
 
 2. Click on Deploy to Kubernetes

In the YAML file you will see: `    name: compose-redis-master-1` for the container name, while I expect there to be `name: redis-master`.

If you set `container_name` within the compose.yaml it works however, which is a odd behaviour.

When Deploying to Kubernetes it should be using the actual container name.
