### ISSUE TITLE
The kubernetes context server link doesn't really help

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman-desktop#4917]
### Bug description

"SERVER"

If you click the link, you only get a page with an invalid certificate and an access denied (when not using the kubeconfig)

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

It should just be normal text, like how the kubernetes connection is shown ?

* https://github.com/containers/podman-desktop/issues/3919

### Operating system

Ubuntu 20.04

### Installation Method

None

### Version

next (development version)

### Additional context

Shouldn't the "server" be shown next to the cluster, not on a separate line ?

```
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: kubernetes
```

```
users:
- name: kubernetes-admin
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
```

Maybe it doesn't need to be shown at all. That is, only show the context?

```
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
```
