### ISSUE TITLE
feat: configured preferred namespace(s) for Kubernetes contexts

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#4990]
### Is your feature request related to a problem? Please describe

When using external cluster, we might want to use a specific namespace by default or we might not have access to the default namespace. 

### Describe the solution you'd like

In the Kubernetes settings, being able to set the preferred namespace.

This settings _could_ be reflected when generating kube.

### Additional context

I do not know if podman-desktop have some kind of internal persistency system ?

**Comment by afbjorklund** [comment]
I think each context has a namespace

```
Usage:
  kubectl config set-context [NAME | --current] [--cluster=cluster_nickname] [--user=user_nickname]
[--namespace=namespace] [options]
```

You can view the current value in CLI:

```console
$ kubectl config get-contexts
CURRENT   NAME        CLUSTER     AUTHINFO    NAMESPACE
*         kind-kind   kind-kind   kind-kind   
```

**Comment by axel7083** [comment]
> I think each context has a namespace
> 
> ```
> Usage:
>   kubectl config set-context [NAME | --current] [--cluster=cluster_nickname] [--user=user_nickname]
> [--namespace=namespace] [options]
> ```
> 
> You can view the current value in CLI:
> 
> ```
> $ kubectl config get-contexts
> CURRENT   NAME        CLUSTER     AUTHINFO    NAMESPACE
> *         kind-kind   kind-kind   kind-kind   
> ```

I don't know how the context would be used specifically in the use case I am seeing. I was thinking for instance, when I am downloading a kubeconfig from rancher for example, it looks like this
```
apiVersion: v1
kind: Config
clusters:
- name: "<name>"
  cluster:
    server: <server>
    certificate-authority-data: <cert>
users:
- name: "<name>"
  user:
    token:  <token>

contexts:
- name: "<name>"
  context:
    user: "<name>"
    cluster: "<name>"

current-context: "<name>"
```

There is no preferred namespace configured, but I do only have access to one namespace, thus, leading to error when importing the config in some Kubernetes dashboards. Some of those dashboard offer a way to configured the "Accessible namespaces"

**Comment by afbjorklund** [comment]
You should be able to add one with `kubectl config set-context <name> --namespace=<name>`

```yaml
contexts:
- context:
    cluster: kind-kind
    namespace: kind-kind
    user: kind-kind
  name: kind-kind
```

The default is empty (and omitted)

https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#working-with-namespaces
