### ISSUE TITLE
An extra "-1" is added to container naming when deploying a compose file. 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5028]
### Bug description

For some reason, Podman Desktop is adding an extra dash and number to container naming when deploying a Compose file:

```yaml
services:

  hello:
    container_name: hello
    image: cdrage/helloworld

  hello-1:
    container_name: hello-1
    image: cdrage/helloworld
```

See below:

![Screenshot 2023-11-28 at 10 35 26 AM](https://github.com/containers/podman-desktop/assets/6422176/587f10d9-90b7-4595-978c-8102dff0c6b0)

Despite the fact that in `podman ps` the naming is fine:

```sh
▶ podman ps
CONTAINER ID  IMAGE                               COMMAND     CREATED             STATUS             PORTS       NAMES
43fad3c6735d  docker.io/cdrage/helloworld:latest              About a minute ago  Up About a minute              hello-1
b9b582c47e64  docker.io/cdrage/helloworld:latest              About a minute ago  Up About a minute              hello
```

### Operating system

mac m1

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Deploy:

```yaml
services:

  hello:
    container_name: hello
    image: cdrage/helloworld

  hello-1:
    container_name: hello-1
    image: cdrage/helloworld
```

Check PD UI and see that an extra `-1` has been added to the name.
