### ISSUE TITLE
Display `containerPort` in the pod group

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#542]
### Is your enhancement related to a problem? Please describe

As a user, I'd like to quickly see the containerPort define in my Pods.

Sample yaml:
```yaml

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.5
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: url_shortener_db
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
````

### Describe the solution you'd like

On the containers in the pod, I should be able to see the containerPort like I do when I start an image
