### ISSUE TITLE
Kubernetes Ingress / Routes page does not show defaultBackend when using no rules.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6107]
### Is your enhancement related to a problem? Please describe

There are some situations where you might encounter an ingress like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: default
spec:
  defaultBackend:
    resource:
      name: 'foobar'
      kind: 'foobar'
```

Where there are no rules, but instead using a defaultBackend and that's it.

This however makes it appear blank in the ingress / routes column:

![Screenshot 2024-02-22 at 9 05 30 AM](https://github.com/containers/podman-desktop/assets/6422176/ccbbe09d-d391-43aa-bed0-55821337c516)

### Describe the solution you'd like

If there are no rules, and there is just a "defaultBackend" (since it can be either rules or backend), we should at least fill in the "backend" portion.
