### ISSUE TITLE
Add "GPU" Label under Roles for Kubernetes clusters that have GPU's detected.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7778]
### Is your enhancement related to a problem? Please describe

![Screenshot 2024-06-21 at 10 57 56 AM](https://github.com/containers/podman-desktop/assets/6422176/cbd367c9-b8aa-48ea-acdc-db0465eb69fe)

It'd be nice to know in the Roles column if a node has a GPU or not.

Just adds a simple "GPU" box to indicate it has one. 

### Describe the solution you'd like

This can be detected by looking under "status" in V1Node.

Example output:

```
status:
  addresses:
    - address: 192.168.1.94
      type: InternalIP
    - address: nvidia1
      type: Hostname
  allocatable:
    cpu: "16"
    ephemeral-storage: "8443296967"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32777408Ki
    nvidia.com/gpu: "1"
    pods: "110"
  capacity:
    cpu: "16"
    ephemeral-storage: 8679376Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32777408Ki
    nvidia.com/gpu: "1"
    pods: "110"
```
    
These allocations / capacity are automatically added when you add the respestive GPU manufacturer's plugins to Kubernetes. 

Below are the labels:

- `nvidia.com/gpu` (via official plugin https://github.com/NVIDIA/k8s-device-plugin)
- `amd.com/gpu` (via official k8s device plugin https://github.com/ROCm/k8s-device-plugin)
- `gpu.intel.com/*` (there are 4, see https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/gpu_plugin/README.md?plain=1#L43)
