### ISSUE TITLE
Include Junit test reporter action in E2E test workflows in Podman desktop repo

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8847]
### Is your enhancement related to a problem? Please describe

It is quite hard to read the log from the e2e test run in order to find out if new test is being run, or what exactly has failed besides downloading the test artifacts. 

### Describe the solution you'd like

there are multiple options to use to visualize e2e test results based on junit report produce by every e2e test run. In podman-desktop-e2e we are using `mikepenz/action-junit-report` which can be configured something like this:
```
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always() # always run even if the previous step fails
      with:
        fail_on_failure: true
        include_passed: true
        detailed_summary: true
        require_tests:  true
        report_paths: '**/*results.xml'
```

Resulting presentation of the test results looks like this: 
![Screenshot_20240911_161246](https://github.com/user-attachments/assets/f8d5eee7-2cfa-4234-9662-f0bd80564a48)
