### ISSUE TITLE
Applying a PVC that is purposely "pending" does not show

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#9322]
### Bug description

Apply a PVC:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

See that it shows in the CLI:

```sh
▶ k get pvc
NAME                        STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
task-pv-claim               Pending                                                                        manual         <unset>                 3m37s
```

It then does not show within the PD k8s UI

### Operating system

mac m1

### Installation Method

None

### Version

1.11.1
