### ISSUE TITLE
kubernetes client is not able to refresh expired credentials on contexts

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#9879]
### Bug description

When the kubernetes client loads the kubeconfig file, it can happen that some credentials are expired. The client should be able to renegociate credentials, with the help of some 3rd-party tools. 

### Operating system

Windows

### Installation Method

Installer from website/GitHub releases

### Version

1.13.3

### Steps to reproduce

See https://github.com/podman-desktop/podman-desktop/issues/8486#issuecomment-2473638614

0. Install az, kubelogin
1. create an AKS cluster, with 'Microsoft Entra ID authentication with Kubernetes RBAC' authn & authz
2. when the cluster is started, partially follow the instructions to connect:
- `az login`
- `az account set --subscription *hidden*`
- `az aks get-credentials --resource-group *hidden* --name *hidden* --overwrite-existing`
- do not execute the command ~`kubelogin convert-kubeconfig -l azurecli`~

3. Your kubeconfig should have the format (note the `--login devicecode` which is important):

``` 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: *hidden*
  name: test
contexts:
- context:
    cluster: test
    user: clusterUser_tests_test
  name: test
current-context: test
kind: Config
preferences: {}
users:
- name: clusterUser_tests_test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      -*hidden*
      - --client-id
      - *hidden*
      - --tenant-id
      - *hidden*
      - --login
      - devicecode
      command: kubelogin
      env: null
      installHint: '

        kubelogin is not installed which is required to connect to AAD enabled cluster.


        To learn more, please go to https://aka.ms/aks/kubelogin

        '
      provideClusterInfo: false
``` 

4. Start Podman Desktop
5. The app should block at the very beginning
6. From another terminal, execute `kubectl get nodes`
7. Follow the instructions to connect
8. Podman Desktop should continue to start
